dist: bionic

sudo: required

services:
- docker

before_install:
- docker pull ubuntu:16.04
- docker pull ubuntu:18.04

env:
 global:
   - KUBE_VERSION=1.12.10-00
   - DOCKER_VERSION=18.06.3~ce~3-0
   - CEPH_VERSION=nautilus
 
jobs:
  include:
    - stage: Base and Ceph Packages
      script:
      - sudo chmod +x ${PWD}/apt-download.sh
      - >
        docker run -t --rm -v ${PWD}/debs:/root/debs -v ${PWD}/apt-download.sh:/root/apt-download.sh ubuntu:16.04 bash -c
        "apt-get update &&
         /root/apt-download.sh 'python python-docker python-chardet python-requests docker-compose chrony jq ipvsadm graphviz nfs-common' &&
         apt-get update && apt-get install -y apt-transport-https curl software-properties-common apt-utils &&
         mkdir /root/debs/ubuntu16 &&
         mv /tmp/debs/*.deb /root/debs/ubuntu16 &&
         cd /root/debs/ubuntu16 &&
         apt-ftparchive packages . > Packages &&
         apt-ftparchive release . > Release"
      - docker build -t wise2c/apt-source:base16 .
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push wise2c/apt-source:base16

    - stage: Base and Ceph Packages
      script:
      - sudo chmod +x ${PWD}/apt-download.sh
      - >
        docker run -t --rm -v ${PWD}/debs:/root/debs -v ${PWD}/apt-download.sh:/root/apt-download.sh ubuntu:18.04 bash -c
        "apt-get update &&
         /root/apt-download.sh 'python python-docker python-chardet python-requests docker-compose chrony jq ipvsadm graphviz nfs-common' &&
         apt-get update && apt-get install -y apt-transport-https curl software-properties-common apt-utils &&
         mkdir /root/debs/ubuntu18 &&
         mv /tmp/debs/*.deb /root/debs/ubuntu18 &&
         cd /root/debs/ubuntu18 &&
         apt-ftparchive packages . > Packages &&
         apt-ftparchive release . > Release"
      - docker build -t wise2c/apt-source:base18 .
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push wise2c/apt-source:base18

    - stage: Base and Ceph Packages
      script:
      - sudo chmod +x ${PWD}/apt-download.sh
      - >
        docker run -t --rm -v ${PWD}/debs:/root/debs -v ${PWD}/apt-download.sh:/root/apt-download.sh ubuntu:16.04 bash -c
        "apt-get update &&
         /root/apt-download.sh 'apt-transport-https curl software-properties-common apt-utils' &&
         apt-get install -y apt-transport-https curl software-properties-common apt-utils &&
         curl -fsSL https://download.ceph.com/keys/release.asc | apt-key add - &&
         echo deb https://download.ceph.com/debian-${CEPH_VERSION}/ xenial main | tee /etc/apt/sources.list.d/ceph.list &&
         apt-get update &&
         /root/apt-download.sh 'ceph ceph-deploy ceph-mgr ceph-mds rbd-nbd rbd-mirror radosgw radosgw-agent open-vm-tools' &&
         mkdir /root/debs/ubuntu16 &&
         mv /tmp/debs/*.deb /root/debs/ubuntu16 &&
         cd /root/debs/ubuntu16 &&
         apt-ftparchive packages . > Packages &&
         apt-ftparchive release . > Release"
      - sudo chmod -R 755 ${PWD}/debs
      - docker build -t wise2c/apt-source:ceph16 .
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push wise2c/apt-source:ceph16

    - stage: Base and Ceph Packages
      script:
      - sudo chmod +x ${PWD}/apt-download.sh
      - >
        docker run -t --rm -v ${PWD}/debs:/root/debs -v ${PWD}/apt-download.sh:/root/apt-download.sh ubuntu:18.04 bash -c
        "apt-get update &&
         /root/apt-download.sh 'apt-transport-https curl software-properties-common apt-utils' &&
         apt-get install -y apt-transport-https curl software-properties-common apt-utils &&
         curl -fsSL https://download.ceph.com/keys/release.asc | apt-key add - &&
         echo deb https://download.ceph.com/debian-${CEPH_VERSION}/ bionic main | tee /etc/apt/sources.list.d/ceph.list &&
         apt-get update &&
         /root/apt-download.sh 'ceph ceph-deploy ceph-mgr ceph-mds rbd-nbd rbd-mirror radosgw radosgw-agent open-vm-tools' &&
         mkdir /root/debs/ubuntu18 &&
         mv /tmp/debs/*.deb /root/debs/ubuntu18 &&
         cd /root/debs/ubuntu18 &&
         apt-ftparchive packages . > Packages &&
         apt-ftparchive release . > Release"
      - sudo chmod -R 755 ${PWD}/debs
      - docker build -t wise2c/apt-source:ceph18 .
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push wise2c/apt-source:ceph18

    - stage: Docker and Kubernetes Packages
      script:
      - docker run -itd --name=base16 wise2c/apt-source:base16
      - docker cp base16:/usr/share/nginx/html/debs base16
      - docker stop base16 && docker rm base16

      - docker run -itd --name=base18 wise2c/apt-source:base18
      - docker cp base18:/usr/share/nginx/html/debs base18
      - docker stop base18 && docker rm base18

      - docker run -itd --name=ceph16 wise2c/apt-source:ceph16
      - docker cp ceph16:/usr/share/nginx/html/debs ceph16
      - docker stop ceph16 && docker rm ceph16

      - docker run -itd --name=ceph18 wise2c/apt-source:ceph18
      - docker cp ceph18:/usr/share/nginx/html/debs ceph18
      - docker stop ceph18 && docker rm ceph18

      - mkdir -p ${PWD}/debs/ubuntu16 && mkdir -p ${PWD}/debs/ubuntu18
      - mv base16/ubuntu16/*.deb ${PWD}/debs/ubuntu16/ && mv base18/ubuntu18/*.deb ${PWD}/debs/ubuntu18/
      - mv ceph16/ubuntu16/*.deb ${PWD}/debs/ubuntu16/ && mv ceph18/ubuntu18/*.deb ${PWD}/debs/ubuntu18/

      - sudo chmod +x ${PWD}/apt-download.sh
      - >
        docker run -t --rm -v ${PWD}/debs:/root/debs -v ${PWD}/kubernetes.list:/root/kubernetes.list -v ${PWD}/apt-download.sh:/root/apt-download.sh ubuntu:16.04 bash -c
        "apt-get update &&
         apt-get install -y apt-transport-https curl software-properties-common apt-utils &&
         curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - &&
         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - &&
         add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable' &&
         cp /root/kubernetes.list /etc/apt/sources.list.d/ &&
         apt-get update &&
         /root/apt-download.sh 'docker-ce=${DOCKER_VERSION}~ubuntu' &&
         /root/apt-download.sh 'kubelet=${KUBE_VERSION} kubectl=${KUBE_VERSION} kubeadm=${KUBE_VERSION}' &&
         cd /tmp/debs &&
         rm -f docker.io*.deb kubelet*.deb kubectl*.deb kubeadm*.deb &&
         apt-get download docker-ce=${DOCKER_VERSION}~ubuntu-xenial libseccomp2 &&
         apt-get download kubelet=${KUBE_VERSION} kubectl=${KUBE_VERSION} kubeadm=${KUBE_VERSION} &&
         echo '##### list docker and kubernetes packages begin #####' &&
         ls docker*.deb &&
         ls kube*.deb &&
         echo '##### list docker and kubernetes packages end #####' &&
         mv /tmp/debs/*.deb /root/debs/ubuntu16 &&
         cd /root/debs/ubuntu16 &&
         apt-ftparchive packages . > Packages &&
         apt-ftparchive release . > Release"

      - >
        docker run -t --rm -v ${PWD}/debs:/root/debs -v ${PWD}/kubernetes.list:/root/kubernetes.list -v ${PWD}/apt-download.sh:/root/apt-download.sh ubuntu:18.04 bash -c
        "apt-get update &&
         apt-get install -y apt-transport-https curl software-properties-common apt-utils &&
         curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - &&
         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - &&
         add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable' &&
         cp /root/kubernetes.list /etc/apt/sources.list.d/ &&
         apt-get update &&
         /root/apt-download.sh 'docker-ce=${DOCKER_VERSION}~ubuntu' &&
         /root/apt-download.sh 'kubelet=${KUBE_VERSION} kubectl=${KUBE_VERSION} kubeadm=${KUBE_VERSION}' &&
         cd /tmp/debs &&
         rm -f docker.io*.deb kubelet*.deb kubectl*.deb kubeadm*.deb &&
         apt-get download 'docker-ce=${DOCKER_VERSION}~ubuntu-bionic libseccomp2' &&
         apt-get download 'kubelet=${KUBE_VERSION} kubectl=${KUBE_VERSION} kubeadm=${KUBE_VERSION}' &&
         echo '##### list docker and kubernetes packages begin #####' &&
         ls docker*.deb &&
         ls kube*.deb &&
         echo '##### list docker and kubernetes packages end #####' &&
         mv /tmp/debs/*.deb /root/debs/ubuntu18 &&
         cd /root/debs/ubuntu18 &&
         apt-ftparchive packages . > Packages &&
         apt-ftparchive release . > Release"
      - sudo chmod -R 755 ${PWD}/debs
      - docker build -t wise2c/apt-source:$TRAVIS_BRANCH .
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push wise2c/apt-source:$TRAVIS_BRANCH
