jobs:
  build-branches-amd64:
    environment:
      CEPH_VERSION: '15.2.9'
      KUBE_VERSION: '1.22.15-00'
      DOCKER_VERSION: '5:20.10.18~3-0'
      OS18: 'xUbuntu_18.04'
      OS20: 'xUbuntu_20.04'
      K8S_VERSION: '1.22'
    machine: true
    steps:
      - checkout
      - run:
     name: Build an amd64 ubuntu20 base container image
     command: |
       sudo chmod +x ${PWD}/apt-download-without-version.sh
       docker run -t --rm -e DEBIAN_FRONTEND=noninteractive -e OS=$OS20 -e VERSION=$K8S_VERSION -v ${PWD}/debs:/root/debs -v ${PWD}/apt-download-without-version.sh:/root/apt-download-without-version.sh ubuntu:20.04 bash -c \
         "rm -f /etc/apt/apt.conf.d/docker-clean && \
          apt-get update && \
          /root/apt-download-without-version.sh "python python3-docker python-chardet python3-requests docker-compose chrony jq ipvsadm graphviz nfs-common gnupg gnupg2 ipset" && \
          mkdir /root/debs/ubuntu20 && \
          mv /tmp/debs/*.deb /root/debs/ubuntu20 && \
          apt-get update && apt-get install -y apt-transport-https curl software-properties-common apt-utils gnupg1 gnupg2 && \
          echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /' > /etc/apt/sources.list.d/devel-kubic-libcontainers-stable.list && \
          cat /etc/apt/sources.list.d/devel-kubic-libcontainers-stable.list && \
          echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /' > /etc/apt/sources.list.d/devel-kubic-libcontainers-stable-cri-o.list && \
          cat /etc/apt/sources.list.d/devel-kubic-libcontainers-stable-cri-o.list && \
          curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | apt-key --keyring /etc/apt/trusted.gpg.d/libcontainers.gpg add - && \
          curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/Release.key | apt-key --keyring /etc/apt/trusted.gpg.d/libcontainers-cri-o.gpg add - && \
          apt-get update && \
          /root/apt-download-without-version.sh 'cri-o cri-o-runc podman' && \
          mv /tmp/debs/*.deb /root/debs/ubuntu20 && \
          ls /root/debs/ubuntu20/"
        docker build -t wise2c/apt-source:base20 .
        #docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        #docker push wise2c/apt-source:base20
